###

GET http://localhost:4006/notes

###
POST  http://localhost:4006/notes
Content-Type: application/json

{
    "title" : "Tugas Backend CRUD",
    "note" : "Selesaikan Tugas Dengan Tepat Waktu"
}

###
PUT http://localhost:4006/notes/title/2
Content-Type: application/json

{
    "title" : "Tugas Trisulaforce Web",
}